-- ===================================================================
-- OWFC Harris — Opponent directory + stock-video folders
-- Two admin-only features:
--   1. `directory`  — contact book of opposition managers, for arranging
--      friendlies. Opponent-ADULT contact info (manager, phone, email,
--      home ground), never child data. Seeded in-app from every distinct
--      fixture opponent; the coach fills in the gaps.
--   2. `drills.folder` — a stock/unassigned video can sit in a named folder
--      on the admin shelf. A video is "stock" when it has NO team assignment
--      AND no child assignment; stock videos are NEVER shown to families.
--
-- Writes are restricted to authenticated users (coaches/parents who sign in).
-- Run in Supabase: SQL Editor -> New query -> Run.
-- ===================================================================

-- ---------- 1. Opponent directory ----------
create table if not exists directory (
  id         bigint generated by default as identity primary key,
  club       text not null,
  manager    text,
  phone      text,
  email      text,
  ground     text,
  created_at timestamptz default now()
);

alter table directory enable row level security;

-- Any signed-in user can read the directory.
drop policy if exists "directory read" on directory;
create policy "directory read" on directory
  for select to authenticated using (true);

-- Any signed-in user can add / edit / remove entries (coach-managed in practice).
drop policy if exists "directory write" on directory;
create policy "directory write" on directory
  for all to authenticated using (true) with check (true);

-- ---------- 2. Stock-video folders ----------
-- Folders are just the set of distinct folder names in use — no separate table.
-- A null folder = unfiled. Stock = team is not true AND player_ids is empty.
alter table drills add column if not exists folder text;
